name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Adapted from examples in https://github.com/goto-bus-stop/setup-zig
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.9.0
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Don't include submodules in linter, as we don't want to lint those anyway
        # with:
        #   submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.9.0
      - run: zig fmt --check src/*.zig
